fixtures:
  forge_modules:
    concat: "puppetlabs/concat"
    firewall: "puppetlabs/firewall"
    logrotate: "puppet/logrotate"
    rsyslog: "saz/rsyslog"
    stdlib: "puppetlabs/stdlib"
    systemd: "puppet/systemd"
