name: Build and publish to Puppet Forge

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest tag
      id: vars
      run: echo "{tag}=${GITHUB_REF:10}" >> $GITHUB_OUTPUT
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        ref: ${{ steps.vars.outputs.tag }}
    - name: Build and publish module
      uses: barnumbirr/action-forge-publish@v2.15.0
      env:
       FORGE_API_KEY: ${{ secrets.FORGE_API_KEY }}
       REPOSITORY_URL: https://forgeapi.puppet.com/v3/releases
